In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
seiz_log = pd.read_excel('GTCS_test.xlsx')
seiz_log.head()

,Index,Name,MRN,Event Type,Data,Visual,Detection Time,False Negative,Bad Seizure,Atypical,Backend
0,0,White Darryl,JH34727961,GTC,"visualization?id=588&userID=588&utc=Fri,%2005%...",NaN,NaN,N,N,N,mongo
1,1,Mark Rabideau,JH46550565,GTC,"visualization?id=10804&userID=10804&utc=Mon,%2...",NaN,NaN,N,N,N,mongo
2,2,Jamella Word,JH42043995,GTC,"visualization?id=589&userID=589&utc=Thu,%2025%...",NaN,NaN,N,N,N,mongo
3,3,Leslie Atoui,JH64134686,GTC,"visualization?id=558&userID=558&utc=Fri,%2026%...",NaN,NaN,N,Y,N,mongo
4,4,Max Thumma,JH16685782,GTC,"visualization?id=558&userID=558&utc=Sun,%2011%...",NaN,NaN,N,N,N,mongo

In [68]:
with open('seizures_raw.json', 'r+') as fp:
    test = json.load(fp)
    test = test[:6]

X = seiz_log['Data']

for i in range(len(X[6:])):
#     test_str = str(X[i+6])
    string = str(X[i+6]).replace(u'\xa0', u' ')
    userID = string[10:15]
    
#     print(test_str)
    
    dat_string = string.split('OVERLAPS')[1]
    start_date = dat_string[3:22]
    end_date = dat_string[26:-2]
    
    data = {
        "damped": False,
        "dataSource": "pg-stage",
        "end": end_date,
        "faked": False,
        "occluded": False,
        "start": start_date,
        "userId": userID 
    }
    
    test.append(data)

with open('seizures_raw.json', 'wt') as fp:
    json.dump(test, fp, indent=4, separators=(',', ': '))

# False Positives

In [85]:
false_pos = pd.read_excel('False Positive Log_258.xlsx')
false_pos

Index(['Participant ', 'TOE', 'HR Baseline', 'HR Peak', 'Payloads', 'Offset',
       'Build'],
      dtype='object')

In [109]:
part = false_pos['Participant ']
data = false_pos['Payloads']
part = list(part)
data = list(data)

false_pos_dict = []
for i in range(len(part)):
    userID = data[0].split("user_id = ")[1][:5]
    start_date = data[0].split("OVERLAPS (\'")[1][:19]
    end_date = data[0].split("OVERLAPS (\'")[1].split(", \'")[1][:19]
    false_pos_dict.append(
    {
        "dataSource": "pg-stage",
        "end": end_date,
        "start": start_date,
        "userId": userID,
        "participant": part[i]
    })

with open("false_positives.json", 'w+') as nf:
    json.dump(false_pos_dict, nf, indent=4, separators=(',', ': '))